/// Generic Dimensions
const MARGIN_ZERO = 0.0;
const MARGIN_SMALL = 4.0;
const MARGIN_MEDIUM = 8.0;
const MARGIN_CARD_MEDIUM_2 = 12.0;
const MARGIN_MEDIUM_2 = 16.0;
const MARGIN_MEDIUM_3 = 20.0;
const MARGIN_LARGE = 24.0;
const MARGIN_XLARGE = 32.0;
const MARGIN_XXLARGE = 48.0;
const MARGIN_XXXLARGE = 60.0;
const MARGIN_XXX_LARGE = 76.0;
const MARGIN_XXXXLARGE = 120.0;

const TEXT_SMALLEST = 8.0;
const TEXT_SMALL = 13.0;
const TEXT_REGULAR = 14.0;
const TEXT_REGULAR_X = 16.0;
const TEXT_REGULAR_2X = 18.0;
const TEXT_REGULAR_3X = 20.0;
const TEXT_HEADING_1X = 24.0;
const TEXT_HEADING_2X = 28.0;
const TEXT_BIG = 32.0;

const BORDER_WIDTH_SMALL = 1.0;
const BORDER_WIDTH_MEDIUM = 2.0;

const TEXT_LINE_HEIGHT = 1.4;

/// App Specific
const LOGIN_TOOLBAR_HEIGHT = 150.0;
const MOVIE_LIST_HEIGHT = 310.0;
const MOVIE_LIST_ITEM_WIDTH = 170.0;
const MOVIE_IMAGE_HEIGHT = 220.0;
const MOVIE_DETAIL_IMAGE_HEIGHT = 250.0;
const MOVIE_DETAIL_IMAGE_WIDTH = 400.0;
const MOVIE_DETAIL_PLOT_HEIGHT = 505.0;
const MOVIE_DETAIL_PLOT_WIDTH = 400.0;
const MOVIE_DETAIL_RADIUS = 40.0;
const PAYMENT_METHOD_COMBO_SET_HEIGHT = 310.0;
const PAYMENT_CONFIRM_CREDIT_CARD_WIDTH = 300.0;
const PAYMENT_CONFIRM_CREDIT_CARD_HEIGHT = 220.0;
const MOVIE_DETAIL_CAST_VIEW_HEIGHT = 80.0;
const MOVIE_DETAIL_CAST_ITEM_WIDTH = 80.0;

const TICKET_WIDTH = 350.0;
const TICKET_HEIGHT = 268.0;
const TICKET_HEIGHT_FOR_QR_CODE = 70.0;
const TICKET_IMAGE_HEIGHT = 205.0;
const TICKET_BOX_RADIUS = 16.0;
const TICKET_SIZED_BOX_WIDTH = 10.0;
const TICKET_SIZED_BOX_HEIGHT = 20.0;
const TICKET_FLEX_SIZED_BOX_WIDTH = 5.0;
const TICKET_FLEX_SIZED_BOX_HEIGHT = 1.0;
const TICKET_BAR_CODE_WIDTH = 250.0;

const PROFILE_IMAGE_SIZE = 56.0;

const MOVIE_ITEM_DATE_LIST_HEIGHT = 88.0;

const MOVIE_GLOSSARY_COLOR_BOX_WIDTH = 25.0;