// Hive Types
const int HIVE_TYPE_ID_USER_VO = 1;
const int HIVE_TYPE_ID_CARD_VO = 2;
const int HIVE_TYPE_ID_REGISTER_AND_LOGIN_VO = 3;
const int HIVE_TYPE_ID_MOVIE_VO = 4;

// Box Names
const String BOX_NAME_USERINFO_VO = "BOX_NAME_USERINFO_VO";
const String BOX_NAME_TOKEN_VO = "BOX_NAME_TOKEN";
const String BOX_NAME_MOVIE_VO = "BOX_NAME_MOVIE_VO";